### ISSUE TITLE
What is this project?

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry/uaa-key-rotator#2]
Just from the title alone & from perusing the source code, this sounds pretty dang interesting. It seems like you're in the middle of rapid development, and doc will likely be changing often, but do you think you could include a little README on what this project is / how you might use it / what it's trying to solve?

Thank you for your time!

**Comment by drnic** [comment]
In the linked story there is a comment to https://github.com/cloudfoundry/identity-ci/blob/master/cf-deployment-ops-files/add-encryption-key.yml which is private. What's in this file?

**Comment by drnic** [comment]
From https://www.pivotaltracker.com/n/projects/997278/stories/156588509/expand it looks that you won't be documenting what this repo is/how to do key rotation until the end of August? Could we get some education on this topic a little sooner plz?

**Comment by aegershman** [comment]
Going to close this, but I hope we get some more info soon. Still intrigued.

Thank you
